Feature/calendar
chi-immigration-task-force/migra-map pull request #9
Opened 2017-03-29 01:39 UTC by rorduno

reafactor calendar

2017-03-29 04:14 UTC, eabedrapo commented
I love your changes @rorduno. I added a few comments on the code but the progress you made with the date picker looks very promising.

I finally found the way to checkout your branch from my fork so I played a little with your code locally. Something that I found a bit challenging was to modify the end date leaving the start date untouched... maybe something we could improve in the future?

Good stuff though!

2017-03-29 04:16 UTC, eabedrapo requested changes
I love your changes @rorduno. I added a few comments on the code but the progress you made with the date picker looks very promising.

I finally found the way to checkout your branch from my fork so I played a little with your code locally. Something that I found a bit challenging was to modify the end date leaving the start date untouched... maybe something we could improve in the future?

Good stuff though!

2017-03-29 04:16 UTC, eabedrapo commented on index.html
> +    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.min.css"/>
Isn't this line the same as line 10?

2017-03-29 04:16 UTC, eabedrapo commented on index.html
> +    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
I think all libraries we import from external sources should go above css/custom.css to we don't overwrite our custom styles... so in this case this line should go above the link tag in line 12.

2017-03-29 04:16 UTC, eabedrapo commented on index.html
>            });
Maybe we should start thinking on moving this JS code into its own file. What do you think?

2017-03-29 04:16 UTC, eabedrapo commented on js/maps_lib.js
>          //-----end of custom initializers-----
Why you didn't remove these lines? Will you need them for the calendar picker?

2017-03-29 04:16 UTC, eabedrapo commented on js/maps_lib.js
Same as above. Or you didn't want to remove the slider logic in case we want to use it in the future? (if so, it's fine with me... I'm just asking 😉 )

2017-03-29 04:16 UTC, eabedrapo commented on js/maps_lib.js
> +
Why I feel like this is duplicating some of the code you have in the HTML?

2017-03-29 16:33 UTC, rorduno commented
@eabedrapo cleaned it up, thanks for the feedback!

2017-03-30 00:14 UTC, eabedrapo approved these changes
Love it!

Well done!

2017-04-03 01:10 UTC, guillermokrh approved these changes
Looks great!

2017-04-03 01:10 UTC, merged